services:
  keycloak:
    container_name: keycloak
    image: ${ECR_URL}/keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_CACHE=ispn
      - KC_CACHE_STACK=ec2
      - JAVA_OPTS=-Djgroups.s3.region_name=ap-northeast-2 -Djgroups.s3.bucket=MY_BUCKET_NAME
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    network_mode: "host"